
IF EXISTS (select * from dbo.sysobjects where id = object_id(N'[dbo].[SP_AFILIADO]') and xtype in (N'FN', N'IF', N'TF', N'P'))
drop procedure [dbo].[SP_AFILIADO] 
GO 
SET ANSI_NULLS ON 
GO 
SET QUOTED_IDENTIFIER ON 
GO 

CREATE PROCEDURE dbo.SP_AFILIADO ( 
  @OPCION_PROCESO int = NULL, 
  @ID INT = NULL , 
  @ID_TERCERO INT = NULL , 
  @ID_TIPO_IDENTIFICACION INT = NULL , 
  @NUM_IDENTIFICACION INT = NULL , 
  @NOMBRES NVARCHAR(200) = NULL , 
  @APELLIDOS NVARCHAR(200) = NULL , 
  @DIRECCION NVARCHAR(500) = NULL , 
  @TELEFONO NVARCHAR(20) = NULL , 
  @FECHA_NACIMIENTO DATE = NULL , 
  @NUM_ACUERDO NVARCHAR(200) = NULL , 
  @ID_NIVEL INT = NULL , 
  @FECHA_INSCRIPCION DATE = NULL , 
  @ID_TIPO_SALARIO INT = NULL 
) 

AS 
BEGIN 
IF @OPCION_PROCESO = 1
BEGIN
select 
ID , 
ID_TERCERO , 
ID_TIPO_IDENTIFICACION , 
NUM_IDENTIFICACION , 
NOMBRES , 
APELLIDOS , 
DIRECCION , 
TELEFONO , 
FECHA_NACIMIENTO , 
NUM_ACUERDO , 
ID_NIVEL , 
FECHA_INSCRIPCION , 
ID_TIPO_SALARIO 
from Nomina.AFILIADO
WHERE (@ID = 0 OR (@ID <> 0 AND ID = @ID)) 
END

IF @OPCION_PROCESO = 2
BEGIN
INSERT INTO Nomina.AFILIADO ( 
  ID_TERCERO , 
  ID_TIPO_IDENTIFICACION , 
  NUM_IDENTIFICACION , 
  NOMBRES , 
  APELLIDOS , 
  DIRECCION , 
  TELEFONO , 
  FECHA_NACIMIENTO , 
  NUM_ACUERDO , 
  ID_NIVEL , 
  FECHA_INSCRIPCION , 
  ID_TIPO_SALARIO 
) VALUES ( 
  @ID_TERCERO , 
  @ID_TIPO_IDENTIFICACION , 
  @NUM_IDENTIFICACION , 
  @NOMBRES , 
  @APELLIDOS , 
  @DIRECCION , 
  @TELEFONO , 
  @FECHA_NACIMIENTO , 
  @NUM_ACUERDO , 
  @ID_NIVEL , 
  @FECHA_INSCRIPCION , 
  @ID_TIPO_SALARIO 
)
--SELECT SCOPE_IDENTITY() 'ID' 
declare @Key int = @@identity
select * from Nomina.AFILIADO where ID = @Key
END
IF @OPCION_PROCESO = 3
BEGIN
UPDATE Nomina.AFILIADO SET 
ID_TERCERO = @ID_TERCERO , 
ID_TIPO_IDENTIFICACION = @ID_TIPO_IDENTIFICACION , 
NUM_IDENTIFICACION = @NUM_IDENTIFICACION , 
NOMBRES = @NOMBRES , 
APELLIDOS = @APELLIDOS , 
DIRECCION = @DIRECCION , 
TELEFONO = @TELEFONO , 
FECHA_NACIMIENTO = @FECHA_NACIMIENTO , 
NUM_ACUERDO = @NUM_ACUERDO , 
ID_NIVEL = @ID_NIVEL , 
FECHA_INSCRIPCION = @FECHA_INSCRIPCION , 
ID_TIPO_SALARIO = @ID_TIPO_SALARIO 
WHERE
ID = @ID 
select * from Nomina.AFILIADO where ID = @ID
END

IF @OPCION_PROCESO = 4
BEGIN
DELETE FROM Nomina.AFILIADO
WHERE 
ID = @ID 
END
IF @OPCION_PROCESO = 5
BEGIN
select 'buenas'
END




END 
GO 


