
IF EXISTS (select * from dbo.sysobjects where id = object_id(N'[dbo].[SP_CIUDAD]') and xtype in (N'FN', N'IF', N'TF', N'P'))
drop procedure [dbo].[SP_CIUDAD] 
GO 
SET ANSI_NULLS ON 
GO 
SET QUOTED_IDENTIFIER ON 
GO 

CREATE PROCEDURE dbo.SP_CIUDAD ( 
  @OPCION_PROCESO int = NULL, 
  @ID INT = NULL , 
  @DESCRIPCION NVARCHAR(50) = NULL , 
  @ID_DEPARTAMENTO INT = NULL 
) 

AS 
BEGIN 
IF @OPCION_PROCESO = 1
BEGIN
select 
ID , 
DESCRIPCION , 
ID_DEPARTAMENTO 
from Gen.CIUDAD
WHERE (@ID = 0 OR (@ID <> 0 AND ID = @ID)) 
END

IF @OPCION_PROCESO = 2
BEGIN
INSERT INTO Gen.CIUDAD ( 
  DESCRIPCION , 
  ID_DEPARTAMENTO 
) VALUES ( 
  @DESCRIPCION , 
  @ID_DEPARTAMENTO 
)
--SELECT SCOPE_IDENTITY() 'ID' 
declare @Key int = @@identity
select * from Gen.CIUDAD where ID = @Key
END
IF @OPCION_PROCESO = 3
BEGIN
UPDATE Gen.CIUDAD SET 
DESCRIPCION = @DESCRIPCION , 
ID_DEPARTAMENTO = @ID_DEPARTAMENTO 
WHERE
ID = @ID 
select * from Gen.CIUDAD where ID = @ID
END

IF @OPCION_PROCESO = 4
BEGIN
DELETE FROM Gen.CIUDAD
WHERE 
ID = @ID 
END
IF @OPCION_PROCESO = 5
BEGIN
select 'buenas'
END




END 
GO 


