
IF EXISTS (select * from dbo.sysobjects where id = object_id(N'[dbo].[SP_CONCEPTOS_AGRUPADOS]') and xtype in (N'FN', N'IF', N'TF', N'P'))
drop procedure [dbo].[SP_CONCEPTOS_AGRUPADOS] 
GO 
SET ANSI_NULLS ON 
GO 
SET QUOTED_IDENTIFIER ON 
GO 

CREATE PROCEDURE dbo.SP_CONCEPTOS_AGRUPADOS ( 
  @OPCION_PROCESO int = NULL, 
  @ID INT = NULL , 
  @ID_CONCEPTO_PADRE INT = NULL , 
  @ID_CONCEPTO_HIJO INT = NULL 
) 

AS 
BEGIN 
IF @OPCION_PROCESO = 1
BEGIN
select 
ID , 
ID_CONCEPTO_PADRE , 
ID_CONCEPTO_HIJO 
from Nomina.CONCEPTOS_AGRUPADOS
WHERE (@ID = 0 OR (@ID <> 0 AND ID = @ID)) 
END

IF @OPCION_PROCESO = 2
BEGIN
INSERT INTO Nomina.CONCEPTOS_AGRUPADOS ( 
  ID_CONCEPTO_PADRE , 
  ID_CONCEPTO_HIJO 
) VALUES ( 
  @ID_CONCEPTO_PADRE , 
  @ID_CONCEPTO_HIJO 
)
--SELECT SCOPE_IDENTITY() 'ID' 
declare @Key int = @@identity
select * from Nomina.CONCEPTOS_AGRUPADOS where ID = @Key
END
IF @OPCION_PROCESO = 3
BEGIN
UPDATE Nomina.CONCEPTOS_AGRUPADOS SET 
ID_CONCEPTO_PADRE = @ID_CONCEPTO_PADRE , 
ID_CONCEPTO_HIJO = @ID_CONCEPTO_HIJO 
WHERE
ID = @ID 
select * from Nomina.CONCEPTOS_AGRUPADOS where ID = @ID
END

IF @OPCION_PROCESO = 4
BEGIN
DELETE FROM Nomina.CONCEPTOS_AGRUPADOS
WHERE 
ID = @ID 
END
IF @OPCION_PROCESO = 5
BEGIN
select 'buenas'
END




END 
GO 


