
IF EXISTS (select * from dbo.sysobjects where id = object_id(N'[dbo].[SP_CONCEPTO_TERCERO]') and xtype in (N'FN', N'IF', N'TF', N'P'))
drop procedure [dbo].[SP_CONCEPTO_TERCERO] 
GO 
SET ANSI_NULLS ON 
GO 
SET QUOTED_IDENTIFIER ON 
GO 

CREATE PROCEDURE dbo.SP_CONCEPTO_TERCERO ( 
  @OPCION_PROCESO int = NULL, 
  @ID INT = NULL , 
  @ID_CONCEPTO INT = NULL , 
  @ID_TERCERO INT = NULL , 
  @DESCRIPCION NVARCHAR(100) = NULL 
) 

AS 
BEGIN 
IF @OPCION_PROCESO = 1
BEGIN
SELECT  CONCEPTO_TERCERO.ID, 
		CONCEPTO_TERCERO.ID_CONCEPTO, 
		CONCEPTO_TERCERO.ID_TERCERO, 
		CONCEPTO_TERCERO.DESCRIPCION,
		CONCEPTO.NOMBRE 'LABEL_CONCEPTO',
		TERCERO.PRIMER_NOMBRE 'LABEL_TERCERO'
FROM         Nomina.CONCEPTO_TERCERO CONCEPTO_TERCERO INNER JOIN
             Nomina.CONCEPTO CONCEPTO  ON CONCEPTO_TERCERO.ID_CONCEPTO = CONCEPTO.ID INNER JOIN
             Gen.TERCERO TERCERO ON CONCEPTO_TERCERO.ID_TERCERO = TERCERO.ID
WHERE (@ID = 0 OR (@ID <> 0 AND CONCEPTO_TERCERO.ID = @ID)) 
END

IF @OPCION_PROCESO = 2
BEGIN
INSERT INTO Nomina.CONCEPTO_TERCERO ( 
  ID_CONCEPTO , 
  ID_TERCERO , 
  DESCRIPCION 
) VALUES ( 
  @ID_CONCEPTO , 
  @ID_TERCERO , 
  @DESCRIPCION 
)
--SELECT SCOPE_IDENTITY() 'ID' 
declare @Key int = @@identity
select * from Nomina.CONCEPTO_TERCERO where ID = @Key
END
IF @OPCION_PROCESO = 3
BEGIN
UPDATE Nomina.CONCEPTO_TERCERO SET 
ID_CONCEPTO = @ID_CONCEPTO , 
ID_TERCERO = @ID_TERCERO , 
DESCRIPCION = @DESCRIPCION 
WHERE
ID = @ID 
select * from Nomina.CONCEPTO_TERCERO where ID = @ID
END

IF @OPCION_PROCESO = 4
BEGIN
DELETE FROM Nomina.CONCEPTO_TERCERO
WHERE 
ID = @ID 
END
IF @OPCION_PROCESO = 5
BEGIN
SELECT  CONCEPTO_TERCERO.ID, 
		CONCEPTO_TERCERO.ID_CONCEPTO, 
		CONCEPTO_TERCERO.ID_TERCERO, 
		CONCEPTO_TERCERO.DESCRIPCION,
		CONCEPTO.NOMBRE 'LABEL_CONCEPTO',
		TERCERO.PRIMER_NOMBRE 'LABEL_TERCERO'
FROM         Nomina.CONCEPTO_TERCERO CONCEPTO_TERCERO INNER JOIN
             Nomina.CONCEPTO CONCEPTO  ON CONCEPTO_TERCERO.ID_CONCEPTO = CONCEPTO.ID INNER JOIN
             Gen.TERCERO TERCERO ON CONCEPTO_TERCERO.ID_TERCERO = TERCERO.ID
where (@ID_TERCERO = -1 or (@ID_TERCERO <> -1 and  CONCEPTO_TERCERO.ID_TERCERO = @ID_TERCERO ))
AND (@ID_CONCEPTO = -1 or (@ID_CONCEPTO <> -1 and CONCEPTO_TERCERO.ID_CONCEPTO = @ID_CONCEPTO))

END




END 
GO 


