
IF EXISTS (select * from dbo.sysobjects where id = object_id(N'[dbo].[SP_DETALLE]') and xtype in (N'FN', N'IF', N'TF', N'P'))
drop procedure [dbo].[SP_DETALLE] 
GO 
SET ANSI_NULLS ON 
GO 
SET QUOTED_IDENTIFIER ON 
GO 

CREATE PROCEDURE dbo.SP_DETALLE ( 
  @OPCION_PROCESO int = NULL, 
  @ID INT = NULL , 
  @ID_MAESTRA INT = NULL , 
  @NOMBRE NVARCHAR(200) = NULL , 
  @DESCRIPCION NVARCHAR(400) = NULL , 
  @CODIGO NVARCHAR(200) = NULL 
) 

AS 
BEGIN 
IF @OPCION_PROCESO = 1
BEGIN
select 
ID , 
ID_MAESTRA , 
NOMBRE , 
DESCRIPCION , 
CODIGO 
from Gen.DETALLE
WHERE (@ID = 0 OR (@ID <> 0 AND ID = @ID)) 
END

IF @OPCION_PROCESO = 2
BEGIN
INSERT INTO Gen.DETALLE ( 
  ID_MAESTRA , 
  NOMBRE , 
  DESCRIPCION , 
  CODIGO 
) VALUES ( 
  @ID_MAESTRA , 
  @NOMBRE , 
  @DESCRIPCION , 
  @CODIGO 
)
--SELECT SCOPE_IDENTITY() 'ID' 
declare @Key int = @@identity
select * from Gen.DETALLE where ID = @Key
END
IF @OPCION_PROCESO = 3
BEGIN
UPDATE Gen.DETALLE SET 
ID_MAESTRA = @ID_MAESTRA , 
NOMBRE = @NOMBRE , 
DESCRIPCION = @DESCRIPCION , 
CODIGO = @CODIGO 
WHERE
ID = @ID 
select * from Gen.DETALLE where ID = @ID
END

IF @OPCION_PROCESO = 4
BEGIN
DELETE FROM Gen.DETALLE
WHERE 
ID = @ID 
END
IF @OPCION_PROCESO = 5
BEGIN
select 'buenas'
END




END 
GO 


