
IF EXISTS (select * from dbo.sysobjects where id = object_id(N'[dbo].[SP_ENTIDAD_RECIPROCA]') and xtype in (N'FN', N'IF', N'TF', N'P'))
drop procedure [dbo].[SP_ENTIDAD_RECIPROCA] 
GO 
SET ANSI_NULLS ON 
GO 
SET QUOTED_IDENTIFIER ON 
GO 

CREATE PROCEDURE dbo.SP_ENTIDAD_RECIPROCA ( 
  @OPCION_PROCESO int = NULL, 
  @ID INT = NULL , 
  @CODIGO NVARCHAR(15) = NULL , 
  @NOMBRE NVARCHAR(80) = NULL , 
  @CONSECUTIVO NVARCHAR(20) = NULL 
) 

AS 
BEGIN 
IF @OPCION_PROCESO = 1
BEGIN
select 
ID , 
CODIGO , 
NOMBRE , 
CONSECUTIVO 
from Gen.ENTIDAD_RECIPROCA
WHERE (@ID = 0 OR (@ID <> 0 AND ID = @ID)) 
END

IF @OPCION_PROCESO = 2
BEGIN
INSERT INTO Gen.ENTIDAD_RECIPROCA ( 
  CODIGO , 
  NOMBRE , 
  CONSECUTIVO 
) VALUES ( 
  @CODIGO , 
  @NOMBRE , 
  @CONSECUTIVO 
)
--SELECT SCOPE_IDENTITY() 'ID' 
declare @Key int = @@identity
select * from Gen.ENTIDAD_RECIPROCA where ID = @Key
END
IF @OPCION_PROCESO = 3
BEGIN
UPDATE Gen.ENTIDAD_RECIPROCA SET 
CODIGO = @CODIGO , 
NOMBRE = @NOMBRE , 
CONSECUTIVO = @CONSECUTIVO 
WHERE
ID = @ID 
select * from Gen.ENTIDAD_RECIPROCA where ID = @ID
END

IF @OPCION_PROCESO = 4
BEGIN
DELETE FROM Gen.ENTIDAD_RECIPROCA
WHERE 
ID = @ID 
END
IF @OPCION_PROCESO = 5
BEGIN
select 'buenas'
END




END 
GO 


