
IF EXISTS (select * from dbo.sysobjects where id = object_id(N'[dbo].[SP_EMPRESA]') and xtype in (N'FN', N'IF', N'TF', N'P'))
drop procedure [dbo].[SP_EMPRESA] 
GO 
SET ANSI_NULLS ON 
GO 
SET QUOTED_IDENTIFIER ON 
GO 

CREATE PROCEDURE dbo.SP_EMPRESA ( 
  @OPCION_PROCESO int = NULL, 
  @ID INT = NULL , 
  @NOMBRE NVARCHAR(200) = NULL , 
  @DIRECCION NVARCHAR(200) = NULL , 
  @TELEFONO NVARCHAR(20) = NULL , 
  @NIT NVARCHAR(20) = NULL 
) 

AS 
BEGIN 
IF @OPCION_PROCESO = 1
BEGIN
select 
ID , 
NOMBRE , 
DIRECCION , 
TELEFONO , 
NIT 
from Nomina.EMPRESA
WHERE (@ID = 0 OR (@ID <> 0 AND ID = @ID)) 
END

IF @OPCION_PROCESO = 2
BEGIN
INSERT INTO Nomina.EMPRESA ( 
  NOMBRE , 
  DIRECCION , 
  TELEFONO , 
  NIT 
) VALUES ( 
  @NOMBRE , 
  @DIRECCION , 
  @TELEFONO , 
  @NIT 
)
--SELECT SCOPE_IDENTITY() 'ID' 
declare @Key int = @@identity
select * from Nomina.EMPRESA where ID = @Key
END
IF @OPCION_PROCESO = 3
BEGIN
UPDATE Nomina.EMPRESA SET 
NOMBRE = @NOMBRE , 
DIRECCION = @DIRECCION , 
TELEFONO = @TELEFONO , 
NIT = @NIT 
WHERE
ID = @ID 
select * from Nomina.EMPRESA where ID = @ID
END

IF @OPCION_PROCESO = 4
BEGIN
DELETE FROM Nomina.EMPRESA
WHERE 
ID = @ID 
END
IF @OPCION_PROCESO = 5
BEGIN
select 'buenas'
END




END 
GO 


