
IF EXISTS (select * from dbo.sysobjects where id = object_id(N'[dbo].[SP_FORMULARIO]') and xtype in (N'FN', N'IF', N'TF', N'P'))
drop procedure [dbo].[SP_FORMULARIO] 
GO 
SET ANSI_NULLS ON 
GO 
SET QUOTED_IDENTIFIER ON 
GO 

CREATE PROCEDURE dbo.SP_FORMULARIO ( 
  @OPCION_PROCESO int = NULL, 
  @ID INT = NULL , 
  @VALOR_TOTAL NUMERIC(22,4) = NULL , 
  @NUMERO_CUOTAS INT = NULL , 
  @VALOR_CUOTA NUMERIC(22,4) = NULL , 
  @OBSERVACIONES NVARCHAR(500) = NULL , 
  @ID_TIPO_FORMULARIO INT = NULL , 
  @ID_TERCERO INT = NULL , 
  @ID_AFILIADO INT = NULL , 
  @ID_DEPENDENCIA INT = NULL 
) 

AS 
BEGIN 
IF @OPCION_PROCESO = 1
BEGIN
select 
ID , 
VALOR_TOTAL , 
NUMERO_CUOTAS , 
VALOR_CUOTA , 
OBSERVACIONES , 
ID_TIPO_FORMULARIO , 
ID_TERCERO , 
ID_AFILIADO , 
ID_DEPENDENCIA 
from Nomina.FORMULARIO
WHERE (@ID = 0 OR (@ID <> 0 AND ID = @ID)) 
END

IF @OPCION_PROCESO = 2
BEGIN
INSERT INTO Nomina.FORMULARIO ( 
  VALOR_TOTAL , 
  NUMERO_CUOTAS , 
  VALOR_CUOTA , 
  OBSERVACIONES , 
  ID_TIPO_FORMULARIO , 
  ID_TERCERO , 
  ID_AFILIADO , 
  ID_DEPENDENCIA 
) VALUES ( 
  @VALOR_TOTAL , 
  @NUMERO_CUOTAS , 
  @VALOR_CUOTA , 
  @OBSERVACIONES , 
  @ID_TIPO_FORMULARIO , 
  @ID_TERCERO , 
  @ID_AFILIADO , 
  @ID_DEPENDENCIA 
)
--SELECT SCOPE_IDENTITY() 'ID' 
declare @Key int = @@identity
select * from Nomina.FORMULARIO where ID = @Key
END
IF @OPCION_PROCESO = 3
BEGIN
UPDATE Nomina.FORMULARIO SET 
VALOR_TOTAL = @VALOR_TOTAL , 
NUMERO_CUOTAS = @NUMERO_CUOTAS , 
VALOR_CUOTA = @VALOR_CUOTA , 
OBSERVACIONES = @OBSERVACIONES , 
ID_TIPO_FORMULARIO = @ID_TIPO_FORMULARIO , 
ID_TERCERO = @ID_TERCERO , 
ID_AFILIADO = @ID_AFILIADO , 
ID_DEPENDENCIA = @ID_DEPENDENCIA 
WHERE
ID = @ID 
select * from Nomina.FORMULARIO where ID = @ID
END

IF @OPCION_PROCESO = 4
BEGIN
DELETE FROM Nomina.FORMULARIO
WHERE 
ID = @ID 
END

IF @OPCION_PROCESO = 5
BEGIN

SELECT  
Nomina.FORMULARIO.ID , 
VALOR_TOTAL , 
NUMERO_CUOTAS , 
VALOR_CUOTA , 
OBSERVACIONES , 
ID_TIPO_FORMULARIO , 
Nomina.FORMULARIO.ID_TERCERO , 
ID_AFILIADO , 
ID_DEPENDENCIA,
GEN.DETALLE.NOMBRE 'TIPO_FORMULARIO',
GEN.TERCERO.PRIMER_NOMBRE 'LABEL_TERCERO',
NOMINA.AFILIADO.NOMBRES 'LABEL_AFILIADO',
NOMINA.DEPENDENCIA.NOMBRE 'LABEL_DEPENDENCIA'
FROM         
Nomina.FORMULARIO	INNER JOIN
Nomina.AFILIADO		ON Nomina.FORMULARIO.ID_AFILIADO = Nomina.AFILIADO.ID INNER JOIN
Nomina.DEPENDENCIA	ON Nomina.FORMULARIO.ID_DEPENDENCIA = Nomina.DEPENDENCIA.ID INNER JOIN
Gen.DETALLE			ON Nomina.FORMULARIO.ID_TIPO_FORMULARIO = Gen.DETALLE.ID INNER JOIN
Gen.TERCERO			ON Nomina.FORMULARIO.ID_TERCERO = Gen.TERCERO.ID


WHERE 
	(@ID_TIPO_FORMULARIO = -1 OR (@ID_TIPO_FORMULARIO <> -1 AND ID_TIPO_FORMULARIO = @ID_TIPO_FORMULARIO)) 
AND	(@ID_TERCERO = -1 OR (@ID_TERCERO <> -1 AND Nomina.FORMULARIO.ID_TERCERO = @ID_TERCERO)) 
AND	(@ID_AFILIADO = -1 OR (@ID_AFILIADO <> -1 AND ID_AFILIADO = @ID_AFILIADO)) 
AND	(@ID_DEPENDENCIA = -1 OR (@ID_DEPENDENCIA <> -1 AND ID_DEPENDENCIA = @ID_DEPENDENCIA)) 





END




END 
GO 


