IF EXISTS (select * from dbo.sysobjects where id = object_id(N'[dbo].[SP_LOGIN_USUARIO]') and xtype in (N'FN', N'IF', N'TF', N'P'))
drop procedure [dbo].[SP_LOGIN_USUARIO] 
GO 
SET ANSI_NULLS ON 
GO 
SET QUOTED_IDENTIFIER ON 
GO 

CREATE PROCEDURE SP_LOGIN_USUARIO (  
	@NICKNAME NVARCHAR(200),
	@PASSWORD NVARCHAR(200)
) 

AS 
BEGIN 

SELECT  
		ID,
		ID_IPS,
		NOMBRES,
		APELLIDOS,
		IDENTIFICACION,
		FECHA_REGISTRO,
		USER_LOGIN,
		PASSWORD,
		ACTIVO
FROM 	Gen.USUARIO  
WHERE 	USER_LOGIN = LTRIM(RTRIM(@NICKNAME)) 
AND 	PASSWORD = LTRIM(RTRIM(@PASSWORD))
AND		ACTIVO = 1

END 
GO 

