
IF EXISTS (select * from dbo.sysobjects where id = object_id(N'[dbo].[SP_ORDEN_PAGO]') and xtype in (N'FN', N'IF', N'TF', N'P'))
drop procedure [dbo].[SP_ORDEN_PAGO] 
GO 
SET ANSI_NULLS ON 
GO 
SET QUOTED_IDENTIFIER ON 
GO 

CREATE PROCEDURE dbo.SP_ORDEN_PAGO ( 
  @OPCION_PROCESO int = NULL, 
  @ID INT = NULL , 
  @ID_ASIGNACION INT = NULL , 
  @ANIO INT = NULL , 
  @MES INT = NULL ,   
  @PORCENTAJE NUMERIC(8,5) = NULL , 
  @VALOR NUMERIC(30,5) = NULL , 
  @PORCENTAJE_EMPLEADO NUMERIC(8,5) = NULL , 
  @PORCENTAJE_EMPRESA NUMERIC(8,5) = NULL , 
  @PRESUPUESTO NVARCHAR(200) = NULL , 
  @CONTABILIDAD NVARCHAR(200) = NULL , 
  @ID_TERCERO INT = NULL ,   
  @ID_ESTADO INT = NULL , 
  @ID_CONCEPTO INT = NULL
) 

AS 
BEGIN 

if @ID_CONCEPTO < 0
begin
	set @ID_CONCEPTO = @ID_CONCEPTO*-1
	SELECT @ID_CONCEPTO = ID FROM NOMINA.CONCEPTO WHERE ID_COMPORTAMIENTO  = @ID_CONCEPTO
	
end

if @ID_TERCERO = 0
begin
	set @ID_TERCERO = null
end


IF @OPCION_PROCESO = 1
BEGIN
select 
ID , 
ID_ASIGNACION , 
ANIO , 
MES , 
PORCENTAJE , 
VALOR , 
PORCENTAJE_EMPLEADO , 
PORCENTAJE_EMPRESA , 
PRESUPUESTO , 
CONTABILIDAD , 
ID_TERCERO , 
ID_ESTADO , 
ID_CONCEPTO
from Nomina.ORDEN_PAGO
WHERE (@ID = 0 OR (@ID <> 0 AND ID = @ID)) 
END
--
IF @OPCION_PROCESO = 2
BEGIN
INSERT INTO Nomina.ORDEN_PAGO ( 
  ID_ASIGNACION , 
  ANIO , 
  MES ,   
  PORCENTAJE , 
  VALOR , 
  PORCENTAJE_EMPLEADO , 
  PORCENTAJE_EMPRESA , 
  PRESUPUESTO , 
  CONTABILIDAD , 
  ID_TERCERO ,    
  ID_ESTADO , 
  ID_CONCEPTO
) VALUES ( 
  @ID_ASIGNACION , 
  @ANIO , 
  @MES ,   
  @PORCENTAJE , 
  @VALOR , 
  @PORCENTAJE_EMPLEADO , 
  @PORCENTAJE_EMPRESA , 
  @PRESUPUESTO , 
  @CONTABILIDAD , 
  @ID_TERCERO ,   
  @ID_ESTADO , 
  @ID_CONCEPTO
)
--SELECT SCOPE_IDENTITY() 'ID' 
declare @Key int = @@identity
select * from Nomina.ORDEN_PAGO where ID = @Key
END

IF @OPCION_PROCESO = 3
BEGIN
UPDATE Nomina.ORDEN_PAGO SET 
ID_ASIGNACION = @ID_ASIGNACION , 
ANIO = @ANIO , 
MES = @MES , 
PORCENTAJE = @PORCENTAJE , 
VALOR = @VALOR , 
PORCENTAJE_EMPLEADO = @PORCENTAJE_EMPLEADO , 
PORCENTAJE_EMPRESA = @PORCENTAJE_EMPRESA , 
PRESUPUESTO = @PRESUPUESTO , 
CONTABILIDAD = @CONTABILIDAD , 
ID_TERCERO = @ID_TERCERO , 
ID_ESTADO = @ID_ESTADO , 
ID_CONCEPTO = @ID_CONCEPTO
WHERE
ID = @ID 
select * from Nomina.ORDEN_PAGO where ID = @ID
END

IF @OPCION_PROCESO = 4
BEGIN
DELETE FROM Nomina.ORDEN_PAGO
WHERE 
ID = @ID 
END

IF @OPCION_PROCESO = 5
BEGIN
SELECT 
ID , 
ID_ASIGNACION , 
ANIO , 
MES , 
PORCENTAJE , 
VALOR , 
PORCENTAJE_EMPLEADO , 
PORCENTAJE_EMPRESA , 
PRESUPUESTO , 
CONTABILIDAD , 
ID_TERCERO , 
ID_ESTADO , 
ID_CONCEPTO
from Nomina.ORDEN_PAGO
WHERE (ID_ASIGNACION = @ID_ASIGNACION) 
END

IF @OPCION_PROCESO = 6
BEGIN
	DELETE FROM Nomina.ORDEN_PAGO
	WHERE ID_ASIGNACION = @ID_ASIGNACION
END


END 
GO 


