
IF EXISTS (select * from dbo.sysobjects where id = object_id(N'[dbo].[SP_USUARIO]') and xtype in (N'FN', N'IF', N'TF', N'P'))
drop procedure [dbo].[SP_USUARIO] 
GO 
SET ANSI_NULLS ON 
GO 
SET QUOTED_IDENTIFIER ON 
GO 

CREATE PROCEDURE dbo.SP_USUARIO ( 
  @OPCION_PROCESO int = NULL, 
  @ID INT = NULL , 
  @ID_IPS INT = NULL , 
  @NOMBRES NVARCHAR(50) = NULL , 
  @APELLIDOS NVARCHAR(50) = NULL , 
  @IDENTIFICACION NVARCHAR(50) = NULL , 
  @FECHA_REGISTRO DATETIME = NULL , 
  @USER_LOGIN NVARCHAR(50) = NULL , 
  @PASSWORD NVARCHAR(50) = NULL , 
  @ACTIVO BIT = NULL 
) 

AS 
BEGIN 
IF @OPCION_PROCESO = 1
BEGIN
select 
ID , 
ID_IPS , 
NOMBRES , 
APELLIDOS , 
IDENTIFICACION , 
FECHA_REGISTRO , 
USER_LOGIN , 
PASSWORD , 
ACTIVO 
from Gen.USUARIO
WHERE (@ID = 0 OR (@ID <> 0 AND ID = @ID)) 
END

IF @OPCION_PROCESO = 2
BEGIN
INSERT INTO Gen.USUARIO ( 
  ID_IPS , 
  NOMBRES , 
  APELLIDOS , 
  IDENTIFICACION , 
  FECHA_REGISTRO , 
  USER_LOGIN , 
  PASSWORD , 
  ACTIVO 
) VALUES ( 
  @ID_IPS , 
  @NOMBRES , 
  @APELLIDOS , 
  @IDENTIFICACION , 
  @FECHA_REGISTRO , 
  @USER_LOGIN , 
  @PASSWORD , 
  @ACTIVO 
)
--SELECT SCOPE_IDENTITY() 'ID' 
declare @Key int = @@identity
select * from Gen.USUARIO where ID = @Key
END
IF @OPCION_PROCESO = 3
BEGIN
UPDATE Gen.USUARIO SET 
ID_IPS = @ID_IPS , 
NOMBRES = @NOMBRES , 
APELLIDOS = @APELLIDOS , 
IDENTIFICACION = @IDENTIFICACION , 
FECHA_REGISTRO = @FECHA_REGISTRO , 
USER_LOGIN = @USER_LOGIN , 
PASSWORD = @PASSWORD , 
ACTIVO = @ACTIVO 
WHERE
ID = @ID 
select * from Gen.USUARIO where ID = @ID
END

IF @OPCION_PROCESO = 4
BEGIN
DELETE FROM Gen.USUARIO
WHERE 
ID = @ID 
END
IF @OPCION_PROCESO = 5
BEGIN
select 'buenas'
END




END 
GO 


